from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import joblib
import os

# ====== Prepare Training Data ======
X_train = [
    # --- Maths ---
    "What is the value of pi?",
    "Solve for x in the equation 2x + 3 = 7.",
    "Calculate the area of a triangle with base 5 and height 10.",
    "What is the Pythagorean theorem?",
    "Find the derivative of x squared.",
    "Simplify the expression 4x + 3x.",
    "What is the formula for the circumference of a circle?",
    "How do you calculate the slope of a line?",
    "Define prime numbers.",
    "What is an integer?",
    "What is a rational number?",
    "What is the formula for the area of a circle?",
    "Solve: 3x - 5 = 1.",
    "What is a square root?",
    "What is a factorial?",
    "How do you convert a decimal to a percentage?",
    "What is the mean of a data set?",
    "Define a geometric progression.",
    "What is a linear equation?",
    "What is a quadratic equation?",
    "How do you plot a graph?",
    "What is the difference between perimeter and area?",
    "What is a fraction?",
    "Explain percentage.",
    "Define LCM and HCF.",
    "What is a vector?",
    "What is the volume of a cube?",
    "What is a matrix?",
    "What is probability?",
    "Solve a simultaneous equation.",
    "Define a parabola.",
    "What is coordinate geometry?",
    "What is differentiation?",
    "What is integration?",
    "What is a modulus function?",
    "Define the slope-intercept form.",
    "What are real numbers?",
    "What is the angle sum property of a triangle?",
    "How do you calculate interest?",
    "What is compound interest?",
    "Define arithmetic mean.",
    "What is a histogram?",
    "What is a bar graph?",
    "What are coordinates?",
    "How to calculate distance between two points?",
    "What is a polygon?",
    "Define a circle.",
    "What is a trapezium?",
    "What is a rhombus?",

    # --- Physics ---
      "Explain Newton’s first law of motion.",
    "Explain Newton’s second law of motion.",
    "What is the formula for force?",
    "Define acceleration.",
    "What is velocity?",
    "Describe the laws of motion.",
    "What is kinetic energy?",
    "What is potential energy?",
    "Explain the concept of momentum.",
    "What is work in physics?",
    "Define power.",
    "What is gravity?",
    "Explain the law of universal gravitation.",
    "What is the speed of light?",
    "Describe electromagnetic waves.",
    "What is sound?",
    "What is a wave?",
    "Explain reflection of light.",
    "What is refraction?",
    "What is friction?",
    "Define pressure.",
    "What is an electric current?",
    "Explain Ohm’s law.",
    "What is voltage?",
    "What is resistance?",
    "What are conductors and insulators?",
    "Describe magnetism.",
    "What is a magnetic field?",
    "Explain the structure of an atom.",
    "What is nuclear energy?",
    "What is thermodynamics?",
    "What is temperature?",
    "Define heat transfer.",
    "What is the difference between scalar and vector quantities?",
    "What is an inclined plane?",
    "Explain the conservation of energy.",
    "What is simple harmonic motion?",
    "Define frequency and wavelength.",
    "What is the Doppler effect?",
    "Describe the photoelectric effect.",
    "What is a circuit?",
    "Explain capacitance.",
    "What is inductance?",
    "What is the principle of buoyancy?",
    "What is the formula for work done?",
    "What is momentum conservation?",
    "Define impulse.",
    "What is fluid dynamics?",
    "What is Bernoulli's principle?",
    "Explain the laws of thermodynamics.",
    "What is an oscillator?",
    "What is nuclear fusion?",

    # --- Chemistry ---
    "What is the chemical formula for water?",
    "What is an acid and what is a base?",
    "Describe the periodic table.",
    "What is the atomic number of carbon?",
    "What is oxidation?",
    "Define ionic bonding.",
    "What is an isotope?",
    "What does the pH scale measure?",
    "What is a covalent bond?",
    "Explain chemical reactions.",
    "What is a catalyst?",
    "Define mole concept.",
    "What are alkanes?",
    "What is valency?",
    "What is an element?",
    "What is a compound?",
    "What is a mixture?",
    "What is electrolysis?",
    "Define atomic mass.",
    "Define molecular mass.",
    "What is Avogadro's number?",
    "What is an exothermic reaction?",
    "What is an endothermic reaction?",
    "Explain distillation.",
    "What is chromatography?",
    "Define neutralization reaction.",
    "What is a salt in chemistry?",
    "What is the universal indicator?",
    "What is a noble gas?",
    "What is the difference between metals and nonmetals?",
    "What is combustion?",
    "What is a chemical equation?",
    "What is the structure of an atom?",
    "Define atomic radius.",
    "What are acids used for?",
    "What are bases used for?",
    "What is rusting?",
    "How to prevent corrosion?",
    "Define electrovalent bond.",
    "What is atomic structure?",
    "What are chemical properties?",
    "What is the law of conservation of mass?",
    "What is a periodic trend?",
    "What is a reaction rate?",
    "What is solubility?",
    "Define a solvent.",
    "Define a solute.",
    "What is a solution?",
    "What is precipitation reaction?",

    # --- Biology ---
    "Explain the process of photosynthesis.",
    "What is DNA?",
    "Name the parts of a plant cell.",
    "What is an ecosystem?",
    "Describe the function of the heart.",
    "What is the human digestive system?",
    "What are mammals?",
    "What is a habitat?",
    "Define evolution.",
    "What do animals eat?",
    "What is respiration?",
    "What is osmosis?",
    "What is diffusion?",
    "What is a gene?",
    "What are chromosomes?",
    "What is a cell?",
    "Define mitosis.",
    "Define meiosis.",
    "What is a tissue?",
    "Name the types of muscles.",
    "What are ligaments?",
    "What are tendons?",
    "What is the function of the liver?",
    "What is the function of the kidney?",
    "What is the nervous system?",
    "What is the skeletal system?",
    "Define reproduction.",
    "What is an ovary?",
    "What is fertilization?",
    "What is an embryo?",
    "What is heredity?",
    "What is immunity?",
    "What is a vaccine?",
    "Name common diseases caused by viruses.",
    "What is a virus?",
    "What are antibiotics?",
    "What is the circulatory system?",
    "What is the function of red blood cells?",
    "What is a producer in a food chain?",
    "What is a consumer in biology?",
    "Define biodiversity.",
    "What is classification of living things?",
    "What is symbiosis?",
    "What are decomposers?",
    "What is chlorophyll?",
    "What is transpiration?",
    "What is the function of roots?",
    "What is the function of leaves?",
    "What is germination?",

    # --- History ---
    "When was the Declaration of Independence signed?",
    "Who was George Washington?",
    "What caused World War II?",
    "Explain the French Revolution.",
    "What was the Renaissance?",
    "Who discovered America?",
    "What is the Industrial Revolution?",
    "Who was Mahatma Gandhi?",
    "Describe the Cold War.",
    "Name some ancient Egyptian pharaohs.",
    "What was the Mughal Empire?",
    "Who was Ashoka the Great?",
    "What is the Harappan Civilization?",
    "Describe the events of 1857 revolt.",
    "What was the role of Subhash Chandra Bose?",
    "What is the meaning of nationalism?",
    "What was the Quit India Movement?",
    "Who was Jawaharlal Nehru?",
    "What is the United Nations?",
    "What is apartheid?",
    "What was the American Civil War?",
    "What is the Berlin Wall?",
    "Who was Adolf Hitler?",
    "Describe India's freedom struggle.",
    "What was the Non-Cooperation Movement?",
    "What was the Dandi March?",
    "What is the Constitution of India?",
    "What is democracy?",
    "Who was Abraham Lincoln?",
    "What is a monarchy?",
    "What was the Great Depression?",
    "What is the history of Indian Railways?",
    "What is feudalism?",
    "What was the Russian Revolution?",
    "What is the Silk Road?",
    "Who were the Vikings?",
    "What was the Cold War?",
    "What is colonialism?",
    "What is imperialism?",
    "Who was Nelson Mandela?",
    "What is World War I?",
    "What was the League of Nations?",
    "Describe the history of Taj Mahal.",
    "Who was Rani Lakshmi Bai?",
    "Who was Bhagat Singh?",
    "What is the history of Indian Parliament?",
    "What are historical monuments?",
    "What is secularism in history?",
    "What is ancient Indian culture?",
    "Who was Chandragupta Maurya?",

    # --- Geography ---
    "What is the capital of France?",
    "Name the longest river in the world.",
    "What are the continents?",
    "Explain the water cycle.",
    "Where is Mount Everest located?",
    "What is a desert?",
    "Define climate.",
    "What causes earthquakes?",
    "Name some countries in Africa.",
    "What is a peninsula?",
    "What is a plateau?",
    "What is a plain?",
    "What is the equator?",
    "What are latitudes and longitudes?",
    "What is a glacier?",
    "What is global warming?",
    "What is deforestation?",
    "What is soil erosion?",
    "What are natural resources?",
    "What is a volcano?",
    "What is a tsunami?",
    "What is a cyclone?",
    "What is weather forecasting?",
    "Define rainfall.",
    "What are oceans?",
    "What is a lake?",
    "What is a delta?",
    "What is an island?",
    "What are the types of forests?",
    "What is the atmosphere?",
    "What is the ozone layer?",
    "What is pollution?",
    "What is urbanization?",
    "What is migration?",
    "What is a map?",
    "What is a compass?",
    "Define population density.",
    "What is human geography?",
    "What is physical geography?",
    "What is a watershed?",
    "What is the Prime Meridian?",
    "What is a national park?",
    "What is biodiversity in geography?",
    "What is land use?",
    "What is sustainable development?",
    "What is a resource map?",
    "What is a topographic map?",
    "What is a contour line?",
    "What are time zones?",
    "What is the Ring of Fire?",
    "How do monsoons affect the climate?",
]

# Create matching labels
subjects = ["maths", "physics", "chemistry", "biology", "history", "geography"]
num_per_subject = len(X_train) // len(subjects)
y_train = [subject for subject in subjects for _ in range(num_per_subject)]


print(f"Length of X_train: {len(X_train)}")
print(f"Length of y_train: {len(y_train)}")

# ====== Build Pipeline ======
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('clf', MultinomialNB())
])

pipeline.fit(X_train, y_train)

# ====== Save the model ======
os.makedirs("app", exist_ok=True)
joblib.dump(pipeline, 'app/model.pkl')
print("✅ Model trained and saved as 'app/model.pkl'")
